### ISSUE TITLE
Change build system to CMake

### ISSUE THREAD

**Issue by KOLANICH** [rgxg/rgxg#4]

**Comment by hvhaugwitz** [comment]
Can you please explain, why you want the build system to be changed to CMake?

**Comment by KOLANICH** [comment]
It is more friendly to changing compilers (including cross-compilers), host and target platforms.

**Comment by AndersonTorres** [comment]
@KOLANICH isn't Cmake a huge software for a so small project? Maybe Meson or Waf would be better choices.

**Comment by KOLANICH** [comment]
No. CMake is the software with minimum dependencies and batteries, but with own large problems, such as bad programming language noone want to touch and a bug tracker and repo in Kitware own GitLab instance noone wants to register, because GitLab instances by default check emails against a blacklist of temporary email services, and even if one took care to register, noone will fix the bug, the bugs stay in CMake bug-tracker for years ignored. Meson is a python package, so requires python, python distros are large and slow to install, noone not already using python wants them. In addition meson has ppor compiler-abstraction layer in the sense of detecting and enabling compiler features without manuall messing with flags.

So for now IMHO CMake is the best. In future I'd prefer even a more declarative build system, where all the features are implemented in the system itsel and all the project dev has to do is to just structure the project in needed way and declare the modules of the build system that should be used, such as something Google blueprint-derived (Unfortunately Soong is android-centered, I have also failed to build it from scratch).

**Comment by hvhaugwitz** [comment]
I don't plan to switch the build system for `rgxg` (as it's a small project with almost no external dependencies). Hence I close this issue as `wontfix`.
