### ISSUE TITLE
Generated regex incorrectly matches

### ISSUE THREAD

**Issue by RoFz** [rgxg/rgxg#8]
rgxg version 0.1.2 here. I'm trying to match a /25 prefix, but the generated regex seems to be incorrect.

This test below should not be a match:

```
$ rgxg cidr 10.1.1.0/25
10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])
$ regexvar="10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])"
$ [[ "10.1.1.129" =~ $regexvar ]] && echo "yes"
yes
$
```

Expected result:

```
$ rgxg cidr 10.1.1.0/25
10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])
$ regexvar="10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])"
$ [[ "10.1.1.129" =~ $regexvar ]] && echo "yes"
$
```

It looks like the issue is the `[1-9]?[0-9]` conditional.

```
$ rgxg cidr 10.1.1.0/25
10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])
$ regexvar="10\.1\.1\.(12[0-7]|1[01][0-9]|[1-9]?[0-9])"
$ [[ "10.1.1.129" =~ $regexvar ]] && echo "yes"
yes
$ [[ "10.1.1.132" =~ $regexvar ]] && echo "yes"
yes
$ [[ "10.1.1.255" =~ $regexvar ]] && echo "yes"
yes
$ [[ "10.1.1.496" =~ $regexvar ]] && echo "yes"
yes
$
```

Am I doing something wrong here?

**Comment by hvhaugwitz** [comment]
Please see the `Notes` section of the manual page (`man 1 rgxg`):

> The regular expressions generated by rgxg are supposed to be used in any context. This may lead to some side effects.
> 
> For instance consider the following:
> ```
> $ echo '192.168.0.999' | grep -E "$(rgxg cidr 192.168.0.0/24)"
> 192.168.0.999
> $
> ```
> This is correct because the regular expression for '192.168.0.0/24' matches '192.168.0.99'.
> 
> One can verify this by adding '-o' to grep:
>
> ```
> $ echo '192.168.0.999' | grep -oE "$(rgxg cidr 192.168.0.0/24)"
> 192.168.0.99
> $
> ```
> As rgxg cannot know in which context the generated regular expression is used, it is up to the user to ensure that the regular expression works as expected (e.g. by adding anchors like '^' and '$').
>
> In the example above adding line anchors leads to the expected behaviour:
> ```
> $ echo '192.168.0.999' | grep -E "^$(rgxg cidr 192.168.0.0/24)$"
> $
> ```

So if you add `^` (matches the starting position within the string) and `$' (matches the ending position within the string) the regular expression works as expected:
```
$ echo 10.1.1.128 | grep -oE --color "^$(rgxg cidr 10.1.1.0/25)$"
$
```
